version: '3'
services:
  distinct-nft-app:
    build:
      context: ./
      dockerfile: Dockerfile
    privileged: true
    ports:
      - '3000:3000'
    env_file:
      - ./.env.development
    restart: always
    networks:
      - net
  distinct_redis_db:
    container_name: distinct-redis-db
    image: 'redis:alpine'
    restart: always
    ports:
      - '6378:6379'
    networks:
      - net
networks:
  net:
